nodeLinker: node-modules

npmScopes:
  mmtplanning:
    npmAuthToken: ya29.a0ARW5m75yYzvQWHts9g2TDBhG1iCq4O_efPH6nEetsE-iuj3-1As_QOU6wK6UFvejUgzMUCQ0nF7NUEi8M2DGPNudcpYMpUNI7oJHfodzyV4E-C31hauF9ac1yeE61y8lhr4xth5D_DYbi9T3GrSV7HZ6efZ3GR_OWan44zqD0QB7k416aCgYKAcESARISFQHGX2Mi8zSAjdypuHEuVqssDhwvJg0183
    npmRegistryServer: "https://us-east4-npm.pkg.dev/directed-reef-420621/simulation-types"

yarnPath: .yarn/releases/yarn-4.3.0.cjs
